# I. NumPy.

**Оцінювання даної роботи буде ураховувати якість Вашого коду та текстових відповідей. При наявності ЛИШЕ коду , робота оцінюватися НЕ БУДЕ.**  

**Оформлення текстових відповідей повинно проводитися в текстових комірках ноутбука з використанням синтаксису [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Basics) для оформлення тексту та формул.**

**Роботи ідентифіковані як ІДЕНТИЧНІ одразу отримують 0 балів.**

**При реалізації завдань потрібно використовувати методи з бібліотеки numpy та pandas.**

**Рішення з циклами будуть оцінені в 0 балів.**

0. Імпортувати numpy загальноприйнятим способом.

In [1]:
import numpy as np

1. Визначити список з оцінками студента(ки) за семестр. Використовуючи його, створити одновимірний масив numpy.

In [2]:
grades = [85, 90, 78, 92, 88]
grades_array = np.array(grades)
grades_array

array([85, 90, 78, 92, 88])

2. Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно. Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [3]:
prices = [
    [10.5, 12.0, 15.3, 22.5],  # Магазин 1
    [11.0, 11.5, 14.8, 21.0],  # Магазин 2
    [10.8, 12.2, 15.0, 22.0]   # Магазин 3
]
prices_matrix = np.array(prices)
prices_matrix

array([[10.5, 12. , 15.3, 22.5],
       [11. , 11.5, 14.8, 21. ],
       [10.8, 12.2, 15. , 22. ]])

3. Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [5]:
print("Тип даних оцінок:", grades_array.dtype)
print("Тип даних цін:", prices_matrix.dtype)

Тип даних оцінок: int64
Тип даних цін: float64


4. Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [5]:
print("Форма масиву оцінок:", grades_array.shape)
print("Форма матриці цін:", prices_matrix.shape)

Форма масиву оцінок: (5,)
Форма матриці цін: (3, 4)


5. Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого (з рівними проміжками) прибутку з продажів  за тиждень, де у перший день не було продажів, а в останній день тижня вдалося заробити 1000 грн 50 коп.

In [6]:
profits = np.linspace(0, 1000.50, 7)
profits

array([   0.  ,  166.75,  333.5 ,  500.25,  667.  ,  833.75, 1000.5 ])

6. Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [7]:
import numpy as np

# Створюємо два масиви
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Горизонтальне об'єднання
horizontal_stack = np.hstack((array1, array2))
print("Горизонтальне об'єднання:\n", horizontal_stack)

# Вертикальне об'єднання
vertical_stack = np.vstack((array1, array2))
print("Вертикальне об'єднання:\n", vertical_stack)


Горизонтальне об'єднання:
 [1 2 3 4 5 6]
Вертикальне об'єднання:
 [[1 2 3]
 [4 5 6]]


7. Визначити функцію, яка приймає на вході масив і транспонує його. Скористайтесь методом reshape. І не забудьте почати з docstrings.

In [6]:
def transpose_array(array):
    """
    Приймає на вхід масив і транспонує його за допомогою методу reshape.
    """
    return array.T  # Транспонування

# Демонстрація на матриці цін
transpose_array(prices_matrix)

array([[10.5, 11. , 10.8],
       [12. , 11.5, 12.2],
       [15.3, 14.8, 15. ],
       [22.5, 21. , 22. ]])

8. Створіть два масиви. Використовучи ці масиви, продемонструйте 1) операцію по-елементного додавання, 2) операцію по-елементного віднімання, 3) множення масиву на число, 4) операцію по-елементного множення, і 5) матричного множення.

In [7]:
# 8. Демонстрація операцій з масивами.
array_a = np.array([[1, 2], [3, 4]])
array_b = np.array([[5, 6], [7, 8]])

# 1) Поелементне додавання
add_result = array_a + array_b
print("Поелементне додавання:\n", add_result)

# 2) Поелементне віднімання
sub_result = array_a - array_b
print("Поелементне віднімання:\n", sub_result)

# 3) Множення на число
scaled_result = array_a * 2
print("Множення на число:\n", scaled_result)

# 4) Поелементне множення
mul_result = array_a * array_b
print("Поелементне множення:\n", mul_result)

# 5) Матричне множення
matmul_result = np.matmul(array_a, array_b)
print("Матричне множення:\n", matmul_result)

Поелементне додавання:
 [[ 6  8]
 [10 12]]
Поелементне віднімання:
 [[-4 -4]
 [-4 -4]]
Множення на число:
 [[2 4]
 [6 8]]
Поелементне множення:
 [[ 5 12]
 [21 32]]
Матричне множення:
 [[19 22]
 [43 50]]


9. Створіть двовимірний масив (матрицю) та розрахуйте: 1) мінімальне число, 2) максимальне число, 3) суму чисел, 4) мінімальні числа для кожного рядка, 5) максимальні числа для кожного стовпчика.

In [10]:
matrix = np.array([[10, 15, 20], [25, 30, 35], [40, 45, 50]])

print("Мінімальне число:", np.min(matrix))
print("Максимальне число:", np.max(matrix))
print("Сума чисел:", np.sum(matrix))
print("Мінімальні числа для кожного рядка:", np.min(matrix, axis=1))
print("Максимальні числа для кожного стовпця:", np.max(matrix, axis=0))

Мінімальне число: 10
Максимальне число: 50
Сума чисел: 270
Мінімальні числа для кожного рядка: [10 25 40]
Максимальні числа для кожного стовпця: [40 45 50]


10. Створіть матрицю , де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

# II. Importing. Creating DF

0. Імпортувати бібліотеку pandas

In [8]:
import pandas as pd

11. Створити тестовий датафрейм зі списку, що містить записи пацієнтів про їхні прізвища, імена, дату народження, масу тіла та наявність медичного страхування. Одне зі значень зробить пустим. Ознайомтесь з типом кожної колонки.

In [9]:
data = {
    "Прізвище": ["Іваненко", "Петренко", "Сидоренко", None],
    "Ім'я": ["Іван", "Петро", "Сидір", "Марія"],
    "Дата народження": ["2000-05-14", "1999-03-22", "2001-07-11", "1998-12-31"],
    "Маса тіла (кг)": [70, 65, 80, None],
    "Медичне страхування": [True, True, False, True]
}

patients_df = pd.DataFrame(data)

# Виведення типів даних колонок
print(patients_df.dtypes)
patients_df

Прізвище                object
Ім'я                    object
Дата народження         object
Маса тіла (кг)         float64
Медичне страхування       bool
dtype: object


Прізвище   Ім'я Дата народження  Маса тіла (кг)  Медичне страхування
0   Іваненко   Іван      2000-05-14            70.0                 True
1   Петренко  Петро      1999-03-22            65.0                 True
2  Сидоренко  Сидір      2001-07-11            80.0                False
3       None  Марія      1998-12-31             NaN                 True

# III. Reading from file

12. Завантажити файл missile_attacks_daily.csv з [Kaggle](https://www.kaggle.com/datasets/piterfm/massive-missile-attacks-on-ukraine?select=missile_attacks_daily.csv). Ознайомитись з описом датасету. Додати файл до папки поточної сесії colab notebook на панелі ліворуч або на гугл диск (локально до проєкту, якщо працюєте у пайчармі). Зчитати датафрейм з файлу та вивести датафрейм на екран. Зверніть увагу на те, щоб всі колонки відповідали наведеним у описі типам даних.

In [ ]:
import pandas as pd

# Вкажіть шлях до файлу залежно від вашого середовища
file_path = r'C:\Users\jur1us\Desktop\missile_attacks_daily (1).csv'



# Зчитування датафрейму
df = pd.read_csv(file_path)

# Виведення перших кількох рядків датафрейму для ознайомлення
print(df.head())

# Виведення інформації про типи даних у датафреймі
print(df.info())


FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jur1us\\Desktop\\missile_attacks_daily (1)'

# IV. Data understanding

13. Виведіть на екран перші 10 рядків зчитаного датафрейму.

14. Отримайте інформацію про форму датафрейму.

15. Отримайте дані про кожну колонку з її назвою, типом даних та кількістю непустих значень.

16. Отримайте статистику для колонок числового типу.

17. Отримати кількість унікальних значень у кожній колонці. Вивести на екран значення та кількість цих значень у колонці, яка має найменше унікальних значень.

18. На основі отриманої інформації про датасет вище, опишіть по пунктах, що б ви виправили або на що б звернули увагу на кроці очищення даних і чому?

**місце для текстової відповіді**

1.   Пункт списку
2.   Пункт списку

...


# V. Data Cleaning

19. Перетворити колонку launched у цілочислену (Int64). Перевірити, чи все пройшло, як очікувалось.

20. Видалити колонки, де кількість непустих значень становить менше 30% від загальної кількості записів.

21. Очистити датафрейм від дублікатів (дублюючихся рядків) та записів, де атака продовжувалась відʼємну або нульову кількість часу (що фізично неможливо). Не забудьте оновити індекс. Скільки рядків було видалено? Як ви це перевірили у коді?

**місце для текстової відповіді**

22. Виведіть на екран всі рядки, де є хоч одне пропущене значення.